steps:
  #################
  # Lint
  #################
  - label: "🧹 Lint"
    command: |
      bundle install
      echo "--- :rubocop: Run Rubocop"
      bundle exec rake rubocop
    if: build.source != "schedule"
    plugins:
      - docker#v3.8.0:
          image: "ruby:2.7.4"

  - label: "Sync"
    command: |
      bundle install
      bundle exec rake sync
    if: build.source == "schedule"
    plugins:
      - docker#v3.8.0:
          image: "ruby:2.7.4"
          propagate-environment: true
          environment:
            # DO NOT MANUALLY SET THIS VALUE!
            # It is passed from the Buildkite agent to the Docker container
            - "VERSION_TOOLKIT_GITHUB_TOKEN"
